apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-kubernetes-component"
  annotations:
    github.com/project-slug: phac008/my-kubernetes-component
    backstage.io/kubernetes-id: "my-kubernetes-component"
    argocd/app-name: "my-kubernetes-component"
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: suxess-it-dev
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
