apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-kubernetes-component"
  annotations:
    github.com/project-slug: phac008/my-kubernetes-component
    backstage.io/kubernetes-id: "my-kubernetes-component"
    argocd/app-name: "my-kubernetes-component"
    backstage.io/techdocs-ref: dir:.
    kubecost.com/deployment-name: my-kubernetes-component
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    grafana/overview-dashboard: "https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-dev&var-workload=my-kubernetes-component&var-service=sx-monitor-demo-app-service"
    vault.io/secrets-path: 'demo/deploydev'
spec:
  type: service
  lifecycle: experimental
  owner: sx-authors
